import { WorkoutHistoryItem } from '../workout-history';

export const MOCK_WORKOUTS: WorkoutHistoryItem[] = [
  {
    id: 'mock-workout-1',
    workout: {
      title: 'Hyrox Session',
      source: 'demo',
      workout_type: 'hiit',
      workout_type_confidence: 0.95,
      blocks: [
        {
          id: 'block-1',
          label: 'Warm-Up',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-1',
              name: 'Row',
              sets: 1,
              reps: null,
              reps_range: null,
              duration_sec: 300,
              rest_sec: 60,
              distance_m: 1000,
              distance_range: null,
              type: 'cardio',
            },
          ],
        },
        {
          id: 'block-2',
          label: 'Hyrox Stations',
          structure: 'rounds',
          rounds: 8,
          rest_between_rounds_sec: 90,
          exercises: [
            {
              id: 'ex-2',
              name: 'Ski Erg',
              sets: null,
              reps: null,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: 1000,
              distance_range: null,
              type: 'cardio',
            },
            {
              id: 'ex-3',
              name: 'Sled Push',
              sets: null,
              reps: null,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: 50,
              distance_range: null,
              type: 'strength',
              notes: '102kg',
            },
            {
              id: 'ex-4',
              name: 'Burpee Broad Jump',
              sets: null,
              reps: 10,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: null,
              distance_range: null,
              type: 'HIIT',
            },
            {
              id: 'ex-5',
              name: 'Wall Ball',
              sets: null,
              reps: 75,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              notes: '9kg ball',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-20T08:30:00Z',
    updatedAt: '2026-02-20T09:45:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-1',
  },
  {
    id: 'mock-workout-2',
    workout: {
      title: 'Upper Body Strength',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.98,
      blocks: [
        {
          id: 'block-3',
          label: 'Push',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-6',
              name: 'Bench Press',
              sets: 4,
              reps: 8,
              reps_range: '6-8',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 2,
              warmup_reps: 5,
            },
            {
              id: 'ex-7',
              name: 'Overhead Press',
              sets: 3,
              reps: 10,
              reps_range: '8-10',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-4',
          label: 'Pull',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-8',
              name: 'Pull-Up',
              sets: 4,
              reps: null,
              reps_range: '6-10',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-9',
              name: 'Cable Row',
              sets: 3,
              reps: 12,
              reps_range: '10-12',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-22T10:00:00Z',
    updatedAt: '2026-02-22T11:10:00Z',
    syncedToStrava: false,
  },
];
