import { WorkoutHistoryItem } from '../workout-history';

export const MOCK_WORKOUT_HISTORY: WorkoutHistoryItem[] = [
  {
    id: 'mock-workout-1',
    workout: {
      title: 'Hyrox Session',
      source: 'demo',
      workout_type: 'hiit',
      workout_type_confidence: 0.95,
      blocks: [
        {
          id: 'block-1',
          label: 'Warm-Up',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-1',
              name: 'Row',
              sets: 1,
              reps: null,
              reps_range: null,
              duration_sec: 300,
              rest_sec: 60,
              distance_m: 1000,
              distance_range: null,
              type: 'cardio',
            },
          ],
        },
        {
          id: 'block-2',
          label: 'Hyrox Stations',
          structure: 'rounds',
          rounds: 8,
          rest_between_rounds_sec: 90,
          exercises: [
            {
              id: 'ex-2',
              name: 'Ski Erg',
              sets: null,
              reps: null,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: 1000,
              distance_range: null,
              type: 'cardio',
            },
            {
              id: 'ex-3',
              name: 'Sled Push',
              sets: null,
              reps: null,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: 50,
              distance_range: null,
              type: 'strength',
              notes: '102kg',
            },
            {
              id: 'ex-4',
              name: 'Burpee Broad Jump',
              sets: null,
              reps: 10,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: null,
              distance_range: null,
              type: 'HIIT',
            },
            {
              id: 'ex-5',
              name: 'Wall Ball',
              sets: null,
              reps: 75,
              reps_range: null,
              duration_sec: null,
              rest_sec: null,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              notes: '9kg ball',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-20T08:30:00Z',
    updatedAt: '2026-02-20T09:45:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-1',
  },
  {
    id: 'mock-workout-2',
    workout: {
      title: 'Upper Body Strength',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.98,
      blocks: [
        {
          id: 'block-3',
          label: 'Push',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-6',
              name: 'Bench Press',
              sets: 4,
              reps: 8,
              reps_range: '6-8',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 2,
              warmup_reps: 5,
            },
            {
              id: 'ex-7',
              name: 'Overhead Press',
              sets: 3,
              reps: 10,
              reps_range: '8-10',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-4',
          label: 'Pull',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-8',
              name: 'Pull-Up',
              sets: 4,
              reps: null,
              reps_range: '6-10',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-9',
              name: 'Cable Row',
              sets: 3,
              reps: 12,
              reps_range: '10-12',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-22T10:00:00Z',
    updatedAt: '2026-02-22T11:10:00Z',
    syncedToStrava: false,
  },
  {
    id: 'mock-workout-3',
    workout: {
      title: 'Lower Body Power',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.97,
      blocks: [
        {
          id: 'block-5',
          label: 'Squat & Deadlift',
          structure: 'sets',
          sets: 5,
          rest_between_sets_sec: 120,
          exercises: [
            {
              id: 'ex-10',
              name: 'Back Squat',
              sets: 5,
              reps: 5,
              reps_range: '4-5',
              duration_sec: null,
              rest_sec: 120,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 3,
              warmup_reps: 5,
            },
            {
              id: 'ex-11',
              name: 'Romanian Deadlift',
              sets: 4,
              reps: 8,
              reps_range: '8-10',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-6',
          label: 'Accessory',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-12',
              name: 'Leg Press',
              sets: 3,
              reps: 12,
              reps_range: '10-15',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-13',
              name: 'Leg Curl',
              sets: 3,
              reps: 12,
              reps_range: '10-15',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-18T07:00:00Z',
    updatedAt: '2026-02-18T08:20:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-3',
  },
  {
    id: 'mock-workout-4',
    workout: {
      title: 'Morning Run',
      source: 'demo',
      workout_type: 'cardio',
      workout_type_confidence: 0.99,
      blocks: [
        {
          id: 'block-7',
          label: 'Easy Run',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-14',
              name: 'Run',
              sets: 1,
              reps: null,
              reps_range: null,
              duration_sec: 2400,
              rest_sec: null,
              distance_m: 5000,
              distance_range: null,
              type: 'cardio',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-17T06:15:00Z',
    updatedAt: '2026-02-17T07:00:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-4',
  },
  {
    id: 'mock-workout-5',
    workout: {
      title: 'Push Day — PPL',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.96,
      blocks: [
        {
          id: 'block-8',
          label: 'Chest',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-15',
              name: 'Bench Press',
              sets: 4,
              reps: 6,
              reps_range: '4-6',
              duration_sec: null,
              rest_sec: 120,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 2,
              warmup_reps: 5,
            },
            {
              id: 'ex-16',
              name: 'Incline Dumbbell Press',
              sets: 3,
              reps: 10,
              reps_range: '8-12',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-9',
          label: 'Shoulders & Triceps',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-17',
              name: 'Overhead Press',
              sets: 4,
              reps: 8,
              reps_range: '6-8',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-18',
              name: 'Lateral Raise',
              sets: 3,
              reps: 15,
              reps_range: '12-15',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-19',
              name: 'Tricep Pushdown',
              sets: 3,
              reps: 12,
              reps_range: '10-15',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-15T09:30:00Z',
    updatedAt: '2026-02-15T10:45:00Z',
    syncedToStrava: false,
  },
  {
    id: 'mock-workout-6',
    workout: {
      title: 'Pull Day — PPL',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.97,
      blocks: [
        {
          id: 'block-10',
          label: 'Back',
          structure: 'sets',
          sets: 4,
          rest_between_sets_sec: 90,
          exercises: [
            {
              id: 'ex-20',
              name: 'Deadlift',
              sets: 4,
              reps: 5,
              reps_range: '3-5',
              duration_sec: null,
              rest_sec: 180,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 3,
              warmup_reps: 3,
            },
            {
              id: 'ex-21',
              name: 'Barbell Row',
              sets: 4,
              reps: 8,
              reps_range: '6-8',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-11',
          label: 'Biceps',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-22',
              name: 'Barbell Curl',
              sets: 3,
              reps: 10,
              reps_range: '8-12',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-23',
              name: 'Hammer Curl',
              sets: 3,
              reps: 12,
              reps_range: '10-15',
              duration_sec: null,
              rest_sec: 60,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-13T10:00:00Z',
    updatedAt: '2026-02-13T11:15:00Z',
    syncedToStrava: false,
  },
  {
    id: 'mock-workout-7',
    workout: {
      title: 'HIIT Cardio Blast',
      source: 'demo',
      workout_type: 'hiit',
      workout_type_confidence: 0.93,
      blocks: [
        {
          id: 'block-12',
          label: 'Intervals',
          structure: 'rounds',
          rounds: 6,
          rest_between_rounds_sec: 60,
          exercises: [
            {
              id: 'ex-24',
              name: 'Assault Bike',
              sets: null,
              reps: null,
              reps_range: null,
              duration_sec: 30,
              rest_sec: 30,
              distance_m: null,
              distance_range: null,
              type: 'cardio',
              notes: 'Max effort',
            },
            {
              id: 'ex-25',
              name: 'Box Jump',
              sets: null,
              reps: 10,
              reps_range: null,
              duration_sec: null,
              rest_sec: 30,
              distance_m: null,
              distance_range: null,
              type: 'HIIT',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-11T07:30:00Z',
    updatedAt: '2026-02-11T08:15:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-7',
  },
  {
    id: 'mock-workout-8',
    workout: {
      title: 'Leg Day — PPL',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.98,
      blocks: [
        {
          id: 'block-13',
          label: 'Squat',
          structure: 'sets',
          sets: 5,
          rest_between_sets_sec: 120,
          exercises: [
            {
              id: 'ex-26',
              name: 'Back Squat',
              sets: 5,
              reps: 5,
              reps_range: '4-6',
              duration_sec: null,
              rest_sec: 120,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              warmup_sets: 3,
              warmup_reps: 5,
            },
          ],
        },
        {
          id: 'block-14',
          label: 'Accessory',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-27',
              name: 'Bulgarian Split Squat',
              sets: 3,
              reps: 10,
              reps_range: '8-12',
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-28',
              name: 'Calf Raise',
              sets: 4,
              reps: 15,
              reps_range: '12-20',
              duration_sec: null,
              rest_sec: 45,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-08T09:00:00Z',
    updatedAt: '2026-02-08T10:20:00Z',
    syncedToStrava: false,
  },
  {
    id: 'mock-workout-9',
    workout: {
      title: 'Zone 2 Bike Ride',
      source: 'demo',
      workout_type: 'cardio',
      workout_type_confidence: 0.99,
      blocks: [
        {
          id: 'block-15',
          label: 'Steady State',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-29',
              name: 'Cycling',
              sets: 1,
              reps: null,
              reps_range: null,
              duration_sec: 3600,
              rest_sec: null,
              distance_m: 25000,
              distance_range: null,
              type: 'cardio',
              notes: 'Zone 2, 130-145bpm',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'garmin',
    createdAt: '2026-02-06T06:00:00Z',
    updatedAt: '2026-02-06T07:05:00Z',
    syncedToStrava: true,
    stravaActivityId: 'strava-mock-9',
  },
  {
    id: 'mock-workout-10',
    workout: {
      title: 'Full Body Conditioning',
      source: 'demo',
      workout_type: 'strength',
      workout_type_confidence: 0.91,
      blocks: [
        {
          id: 'block-16',
          label: 'Compound Lifts',
          structure: 'regular',
          exercises: [
            {
              id: 'ex-30',
              name: 'Deadlift',
              sets: 3,
              reps: 5,
              reps_range: null,
              duration_sec: null,
              rest_sec: 180,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-31',
              name: 'Bench Press',
              sets: 3,
              reps: 8,
              reps_range: null,
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
            {
              id: 'ex-32',
              name: 'Back Squat',
              sets: 3,
              reps: 8,
              reps_range: null,
              duration_sec: null,
              rest_sec: 90,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
        {
          id: 'block-17',
          label: 'Finisher',
          structure: 'rounds',
          rounds: 3,
          rest_between_rounds_sec: 60,
          exercises: [
            {
              id: 'ex-33',
              name: 'Kettlebell Swing',
              sets: null,
              reps: 20,
              reps_range: null,
              duration_sec: null,
              rest_sec: 30,
              distance_m: null,
              distance_range: null,
              type: 'strength',
              notes: '24kg',
            },
            {
              id: 'ex-34',
              name: 'Push-Up',
              sets: null,
              reps: 15,
              reps_range: null,
              duration_sec: null,
              rest_sec: 30,
              distance_m: null,
              distance_range: null,
              type: 'strength',
            },
          ],
        },
      ],
    },
    sources: ['demo'],
    device: 'apple',
    createdAt: '2026-02-04T08:30:00Z',
    updatedAt: '2026-02-04T09:45:00Z',
    syncedToStrava: false,
  },
];
